export enum EActions {
  SET_SPENT = 'SET_SPENT',
  SET_ACCOUNT = 'SET_ACCOUNT',
  SET_PANE = 'SET_PANE',
  LOAD_TRANSACTIONS = 'LOAD_TRANSACTIONS',
  SAVE_TRANSACTIONS = 'SAVE_TRANSACTIONS',
  SET_TRANSACTIONS = 'SET_TRANSACTIONS',
  ADD_TRANSACTIONS = 'ADD_TRANSACTIONS',
  UPDATE_TRANSACTIONS = 'UPDATE_TRANSACTIONS',
  POST_TRANSACTION = 'POST_TRANSACTION',
  SELECT_TRANSACTION = 'SELECT_TRANSACTION',
  HIDE_TRANSACTION = 'HIDE_TRANSACTION',
  UNHIDE_TRANSACTION = 'UNHIDE_TRANSACTION',
  UPDATE_TRANSACTION_NOTES = 'UPDATE_TRANSACTION_NOTES'
}
